@startuml
hnote over Main : Load products,\nportions and\nload actors 

Main -> Waiter : Trigger launch 
hnote over Waiter : Ask for information 

Waiter -> Coq: Meal request

Coq --> Intendant: Main ingredient request
Intendant --> Coq: Main ingredient response

loop x times with number_of_dispensers as x
    Coq --> Dispensers: Other ingredients request
    Dispensers --> Coq: Other ingredients response
end

hnote over Coq : Choice of ingredients

Coq --> Intendant: Quantity request
hnote over Intendant : Quantity choice 
Intendant --> Coq: Quantity answer

Coq --> Waiter: Meal answer
hnote over Waiter : Print meal 
@enduml